---
apt_repositories:
  - deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse
  - deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} multiverse
  - deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse
  - deb-src http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}}-updates multiverse
  - ppa:git-core/ppa
  - ppa:videolan/stable-daily
  - ppa:webupd8team/java
  - ppa:fkrull/deadsnakes-python2.7
required_software_apt:
  - software-properties-common
  - apt-cacher-ng
  - python
  - curl
  - vim
  - zip
  - language-pack-en
  - python-pip
  - git
  - build-essential
  - virtualbox-guest-dkms
  - virtualbox-guest-utils
  - virtualbox-guest-x11
additional_software:
  - thunderbird
  - nvidia-settings
  - vlc
required_software_pip:
  - ansible
  - boto
  - virtualenv

role_syncthing_user: vagrant
device_kickseed:
  - id: FO5C75X-QGMCTZM-HN2YLA4-ZOQ6VYK-D2AOP7O-DVMX7K5-CO7KBUU-AEFVEAG
    name: "kickseed"
role_syncthing_data:
  folders:
    - inventory_hosts: '{{ groups.all }}'
      path: '/home/vagrant/sync'
      id: 'devbox_sync'
      devices_add:
        - "{{ device_kickseed }}"
    - inventory_hosts: '{{ groups.all }}'
      path: '/home/vagrant/Videos'
      id: 'videos'
      devices_add:
        - "{{ device_kickseed }}"
