---
- hosts: localhost
  connection: local
  pre_tasks:
    - include_vars: group_vars/secure.yml
      ignore_errors: true

    - name: Add the docker role
      become: yes
      group:
        name: docker
        state: present

    - name: Add the vagrant user to the docker role
      become: yes
      user:
        append: yes
        groups: docker
        name: vagrant
      register: docker_group

  roles:
    - { role: nexeck.docker, become: yes }
    - { role: rallen-temp.ansible-zsh }
    - { role: vcabourdin.chrome, become: yes }
    - { role: hutchic.btsync, become: yes, when: btsync_user.user is defined }

  post_tasks:
    - name: Change default shell to zsh
      become: yes
      command: chsh -s /usr/bin/zsh vagrant

    - name: Reboot
      become: yes
      command: reboot now
      when: docker_group.changed
