---
- hosts: localhost
  connection: local
  pre_tasks:
    - include_vars: group_vars/secure.yml
      ignore_errors: true

    - name: Add the docker role
      become: yes
      group:
        name: docker
        state: present

    - name: Add the vagrant user to the docker role
      become: yes
      user:
        append: yes
        groups: docker
        name: vagrant
      register: docker_group

    - name: Is btsync already installed
      become: yes
      stat: path=/usr/local/bin/btsync
      register: btsync

    - name: Is docker already installed
      become: yes
      stat: path=/usr/bin/docker
      register: docker

    - name: Is zsh already installed
      become: yes
      stat: path=/bin/zsh
      register: zsh

    - name: Is google chrome already installed
      become: yes
      stat: path=/usr/bin/google-chrome
      register: chrome

    - name: Is atom already installed
      become: yes
      stat: path=/usr/bin/atom
      register: atom

  roles:
    - { role: nexeck.docker, become: yes, when: docker.stat.exists == False }
    - { role: rallen-temp.ansible-zsh, when: zsh.stat.exists == False }
    - { role: vcabourdin.chrome, become: yes, when: chrome.stat.exists == False }
    - { role: ansibl3.deb_atom, become: yes, when: atom.stat.exists == False }

  post_tasks:
    - name: Change default shell to zsh
      become: yes
      command: chsh -s /usr/bin/zsh vagrant

    - name: Install additional software packages
      become: yes
      apt:
        name: "{{ item }}"
        state: "latest"
        update_cache: yes
      with_items: "{{ additional_software }}"
      ignore_errors: yes

    - name: Reboot
      become: yes
      command: reboot now
      when: docker_group.changed
